apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-profile-init
  namespace: {{ include "arch.namespace" . }}
data:
  001_schema.sql: |
    CREATE TABLE profile (
      profile_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      userid bigint NOT NULL,
      name varchar(255),
      surname varchar(255),
      date_of_birth timestamp,
      gender varchar(20),
      city varchar(255),
      bio text,
      interests text,
      status varchar(255),
      CONSTRAINT uq_user
      UNIQUE (userid)
    );
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-profile-secret
  namespace: {{ include "arch.namespace" . }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresProfile.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresProfile.password | quote }}
  POSTGRES_DB: {{ .Values.postgresProfile.database | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-profile
  namespace: {{ include "arch.namespace" . }}
  labels:
    app: postgres-profile
spec:
  clusterIP: None
  selector:
    app: postgres-profile
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-profile
  namespace: {{ include "arch.namespace" . }}
  labels:
    app: postgres-profile
spec:
  serviceName: postgres-profile
  replicas: 1
  selector:
    matchLabels:
      app: postgres-profile
  template:
    metadata:
      labels:
        app: postgres-profile
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresProfile.image }}
          ports:
            - name: pg
              containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-profile-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgresProfile.user | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgresProfile.user | quote }}]
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
      volumes:
        - name: init
          configMap:
            name: postgres-profile-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresProfile.storage }}
